FROM rust:alpine AS builder

RUN apk update
RUN apk add clang musl-dev
RUN mkdir slave
COPY . slave/
RUN cd slave && cargo build --bin slave --release
RUN strip /slave/target/release/slave

FROM busybox

COPY --from=builder /slave/target/release/slave .

ENTRYPOINT ["/slave"]
