FROM rust:alpine AS builder

RUN apk update
RUN apk add clang musl-dev
RUN mkdir server
COPY . server/
RUN cd server && cargo build --bin server --release
RUN strip /server/target/release/server

FROM docker

COPY --from=builder /server/target/release/server .

ENTRYPOINT ["/server"]
