version: "3.9"

services:
  server:
    image: itytophile/hash-server
    ports:
      - "3000:3000"
  slave:
    image: itytophile/hash-slave
    depends_on:
      - server
    command: /slave ws://server:3000/ws
  monitor:
    image: itytophile/monitor
    depends_on:
      - server
    command: /monitor -a ws://server:3000/ws
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock