FROM rust AS builder

COPY . .
RUN mkdir .cargo && cp docker/config.toml .cargo/
RUN RUSTFLAGS='-C target-feature=+crt-static' cargo build --bin slave --release --target x86_64-unknown-linux-gnu
RUN strip target/x86_64-unknown-linux-gnu/release/slave

FROM busybox:glibc

COPY --from=builder target/x86_64-unknown-linux-gnu/release/slave .

RUN rm -r /bin

CMD ["/slave"]
